"""empty message

Revision ID: 12db95cb5a33
Revises: e0e647ac003c
Create Date: 2026-03-16 11:36:36.346146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12db95cb5a33'
down_revision = 'e0e647ac003c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('password')

    # ### end Alembic commands ###
